#      ___                                  __  ___            __   ______
#     /   |  _____ _____ ___   _____ _____ /  |/  /____   ____/ /  / ____/
#    / /| | / ___// ___// _ \ / ___// ___// /|_/ // __ \ / __  /  /___ \
#   / ___ |/ /__ / /__ /  __/(__  )(__  )/ /  / // /_/ // /_/ /  ____/ /
#  /_/  |_|\___/ \___/ \___//____//____//_/  /_/ \____/ \__,_/  /_____/
## General parameters and configuration list 

# load main packages.
library(shiny)
library(devtools)

# shiny options 
options(
  shiny.maxRequestSize = 300*1024^2 
  #,shiny.trace=TRUE
)


# output config list:
config<-list()


# List of packages to load or install from CRAN (loaded in session to handle updates...)
config$packagesCran= c(
  "shiny",
  "devtools",
  "shinydashboard", # tools to produce admin LTE ui with shiny
  "rgrass7", # R interface to GRASS GIS
  "tools", # base tools and file utilities
  "htmltools", # html tools, companion of shiny.
  "data.table", # faster than data.frame for large data processing.
  "devtools", # development tools
  "raster", #class and function for raster map
  "rgdal", #intern gdal command
  "rgeos",# map manipulation
  "maps", # download and display generic maps
  "rjson", # read json formated file (e.g geojson)
  "gdalUtils", # launch system gdal command from R
  "RSQLite", # interface to SQLITE database
  #"gdata", # enable compatibility with read.xls (and xlsx files)
  #"readODS",# read ods files
  "plyr", # data manipulation
  "pingr" # ping remote server. Used in update process
)

# List of packages to load or install from Github
config$packagesGithub<-c(
  'Rcpp'="RcppCore/Rcpp",# Lastest version of Rcpp
  'leaflet'="fxi/AccessMod_leaflet-shiny",
  'shinydashboard'="rstudio/shinydashboard",# UI
  'geojsonio'="ropensci/geojsonio",
  'readxl'="hadley/readxl", # https://github.com/hadley/readxl read excel
  'rio'="leeper/rio" #https://github.com/leeper/rio universal table import 
)

#Paths
# base directory.
config$pathModule<-normalizePath('modules/')
config$pathGrassHome<-normalizePath('../logs/')
config$pathGrassDataBase<-normalizePath('../data/grass/')
config$pathCacheDir<-normalizePath('../data/cache')
config$pathLib<-normalizePath('../libs/')
# set local lib as first choice:
.libPaths( c(config$pathLib, .libPaths())) 
# sqlite database
# get sqlite path after grass init : system(paste("echo",sqliteDB),intern=TRUE)
config$pathSqliteDB<-'$GISDBASE/$LOCATION_NAME/$MAPSET/sqlite.db'


# create directories if necessary.
dir.create(showWarnings=F,recursive=T,config$pathGrassDataBase)
dir.create(showWarnings=F,config$pathGrassHome)
dir.create(showWarnings=F,config$pathLib)
dir.create(showWarnings=F,config$pathCacheDir)


# set other grass variables
# TODO: check if is use:
#grassMapset<-"PERMANENT"
grassRcFile<-file.path(config$pathGrassHome,'.grassrc6')
# unset gis_lock on startup
#unset.GIS_LOCK()

# standard dem name
config$mapDem<-"dem__dem@PERMANENT"

# grass binaries and libs
config$os<-system("uname",intern=TRUE)
if(config$os=="Darwin"){
  config$pathGrassBase70="/usr/local/Cellar/grass-70/7.0.0/grass-7.0.0"
  config$pathGrassBase64="/usr/local/Cellar/grass-64/6.4.4_1/grass-6.4.4"
}else{
  # expect to be run on linux.. so default are :
  config$pathGrassBase70="/usr/local/grass-7.0.0"
  config$pathGrassBase64="/usr/lib/grass64"
}

# store archive in mapset.
# get archive path after grass init : system(paste("echo",archives),intern=TRUE)
config$pathArchiveGrass<-'$GISDBASE/$LOCATION_NAME/$MAPSET/accessmodArchives'
config$pathArchiveBaseName<-'accessmodArchive'


# log file. must create it does not exist 
config$pathLog<-normalizePath(file.path(config$pathGrassHome,'logs.txt'))
if(!file.exists(config$pathLog)) write("",config$pathLog)


#global variables
config$amLocation<-""
config$amTitle<-'Accessmod 5.0' # todo : include GIT version.

#standard message 
# TODO: These message are depreciated. Check and update function where they are used.
# TODO: create real localisation ?  (*.po/*.mo) 
config$msgNoLocation=list(en="Please select or create a project")
config$msgNoLocMapset=list(en="Please select or create project.")
config$msgNoProj<-'No projection information found. Make sure your dataset contains such information : .prj file, adf.prj, worldFile, complete metadata or similar.'
config$msgNotMetric<-'No metric projection information found. Make sur your dataset is projected using a metric coordinate system.'


# Registery of encountered errors NOT GENERATED BY ACCESSMOD. 
# Add new hint and translation in human language to avoid users to panic.
# This list, with function errHandler(), should dispatch current error to warning, log, or error condition.
# only warning and error (as set here or in amMsg() function) will create an alert for the user.
# structure :
# a. cond : hint of the registered condition. As the condition could be concatenated: (e.g. "SimpleWarning: 23 feature missing in map coverage@demo500m" ), extract only the useful part: "feature missing in map".  
# b. desc : Description to understand the error from the developer point of view.
# c. type : how accessMod should interprets the condition : log or error ?
# c. text : replacement text for the user.

config$msgTableError<-as.data.frame(rbind(
  c(
    cond="is a base map for",
    desc="small warning when removing tmp map used in mask.",
    type='log',
    text='base map removed'
    ),
  c(
    cond= "No areas selected from vector map",
    desc=" v.to.rast warning if convert area is selected, but not found in geometries.",
    type='log',
    text='Vector map conversion to raster without area'
    ),
  c(
    cond="not recognised by GRASS",
    desc=" maybe a wrong text. TODO: control this one. The text could be the original message.",
    type='log',
    text='Datum <unknown> not recognised by GRASS'
    ),
  c(
    cond="file does not exists",
    desc="Error after upload wrong file (type doesn't match extension, no metadata) OR error during gdal operation OR shiny internal fileUpload i/o problem.",
    type="error",
    text="file not recognized, make sure you have uploaded a supported raster files, with all its dependencies."
    ),
  c(
    cond="already exists and will",
    desc= "Warning/error that occurs  with flag 'overwrite' and map exists.", 
    type="log",
    text="Map has been overwritten"
    ),
  c(
    cond="had status 1",
    desc=" generic error : could be everything. For now, tell the users it could be due to a bad formated dataset.",
    type="Error",
    text="Process has been aborded. Check your data for anomalies, e.g.: extent, CRS, non-conform values."
    ),
  c(
  cond="not appear to match current location",
  desc=" if the map crs is clearly wrong",
    type="error",
    text="The map CRS did not match current location."
    ),
  c(
    cond="Cannot create a RasterLayer object from this file",
    desc=" Error during importation if the package raster cant read metadata.",
    type="error",
    text="File not recognized, make sure you have loaded a supported raster map format, with all dependencies."
    ),
  c(
    cond="were not modified because modification would damage",
    desc= "v.clean say that some features has not ben cleaned to preserve topology",
    type='log',
    text='v.clean topology warning : some features have not been cleaned'
    ),
  c(
    cond="are written only when -c flag is given",
    desc='Warning when exporting empty area (inner rings) to shapefile',
    type="log",
    text="v.out.ogr found empty area (inner rings) to export in shapefile."
    ),
  c(
    cond="WARNING: Number of duplicate centroids",
  desc='duplicate centroids',
  type="log",
  text="v.in.ogr found duplicate centroïd"
  )
)
  )

# ui dimension. New method : use class and CSS file
# NOTE: check accessMod.css in www instead !
#
#dimsbw=3 # sidebarpanel width
#dimmpw=9 # main panel width
#stybtn="width:95%" # btn style
#stytxt="width:90%" # btn style
#dimselw="100%" # selectinput width
#
# verbose mode. 
# TODO: check if this is used
config$verbMod<-TRUE



# file extension allowed See also validateFilExt in fun/helper.R
config$fileAdf<-c('dblbnd.adf','hdr.adf','prj.adf','vat.adf','w001001.adf','w001001x.adf')
config$fileAdfMin<-c('prj.adf','w001001.adf','hdr.adf')
config$fileShpExt<-c('.shp','.dbf','.prj','.sbn','.sbx','xml','.shx')
config$fileShpExtMin<-c('.shp','.prj','.dbf','.shx')

config$filesAccept<-list(
  "vector"=c('.sqlite','.spatialite',config$fileShpExt),
  "raster"=c('.adf','.geotiff','.GeoTIFF','.tiff'),
  "table"=c('.xls','.csv','.xlsx','.ods')
  )

config$fileAcceptMultiple<-list(
  "vector" = TRUE,
  "raster" = TRUE,
  "table" = FALSE 
  )

config$tableColNames<-list(
  'table_model'=c('class','label','speed','mode'),
  'table_land_cover'=c('class','label'),
  'table_stack_road'=c('class','label')
  )

# table of available class, and which are allowed as new dataset input.
# TODO: add visibility in module manageData : devel, user, admin..
# Weird method to input a new table, but.. This table could/will be stored in csv file
# or in a database.. 
config$dataClass<-read.table(text=paste("
id , class                       , type   , colors       , allowNew , internal\n
1  , dem                         , raster , elevation    , FALSE    , FALSE\n
2  , land_cover                  , raster , random       , TRUE     , FALSE\n
3  , population                  , raster , population&e , TRUE     , FALSE\n
4  , population_residual         , raster , population&e , FALSE    , FALSE\n
5  , population_on_barrier       , raster , population&e , FALSE    , FALSE\n
6  , barrier                     , vector ,              , TRUE     , FALSE\n
7  , road                        , vector ,              , TRUE     , FALSE\n
8  , health_facilities           , vector ,              , TRUE     , FALSE\n
9  , zone_admin                  , vector ,              , TRUE     , FALSE\n
10 , speed                       , raster , bcyr&e       , FALSE    , TRUE\n
11 , friction                    , raster , bcyr&e       , FALSE    , TRUE\n
12 , merged                      , raster , random       , FALSE    , FALSE\n
13 , merged_bridge               , raster , random       , FALSE    , TRUE\n
14 , cumulative_cost             , raster , slope        , FALSE    , FALSE\n
15 , table_land_cover            , table  ,              , TRUE     , FALSE\n
16 , table_model                 , table  ,              , TRUE     , FALSE\n
17 , table_referral              , table  ,              , FALSE    , FALSE\n
18 , table_referral_nearest_dist , table  ,              , FALSE    , FALSE\n
19 , table_referral_nearest_time , table  ,              , FALSE    , FALSE\n
20 , table_capacity              , table  ,              , FALSE    , FALSE\n
21 , table_zonal_coverage        , table  ,              , FALSE    , FALSE\n
22 , stack_road                  , raster , random       , FALSE    , TRUE\n
23 , stack_land_cover            , raster , random       , FALSE    , TRUE\n
24 , stack_barrier               , raster , random       , FALSE    , TRUE\n
"),
sep=',',
header=TRUE,
colClasses=c('integer','character','character','character','logical','logical'),
strip.white=TRUE
)

# character separator
config$sepTagUi='+'
config$sepTagFile='_'
config$sepClass='__'
config$sepTagRepl=' '
config$sepMapset='@' 

# max row table preview
config$maxRowPreview<-50

# allowed mode of transportation. required as it by r.walk.accessmod.
config$listTranspMod<-list(
  WALKING=list(rastVal=1000),
  BICYCLING=list(rastVal=2000),
  MOTORIZED=list(rastVal=3000)
  )


# color palettes
config$paletteBlue<-colorRampPalette(c("#FFFFFF","#8C8CB2","#004664","#000632","#000000"))


# incons
# icon/favicon, defined in ui.R
config$iconSmall<-img(src="logo/icons/logo24x24.png")
config$iconMedium<-img(src="logo/icons/logo32x32.png")
config$iconLarge<-img(src="logo/icons/logo128x128.png")
config$iconHuge<-img(src="logo/icons/logo648x648.png")

# order config list
config<-config[sort(names(config))]

