#      ___                                  __  ___            __   ______
#     /   |  _____ _____ ___   _____ _____ /  |/  /____   ____/ /  / ____/
#    / /| | / ___// ___// _ \ / ___// ___// /|_/ // __ \ / __  /  /___ \
#   / ___ |/ /__ / /__ /  __/(__  )(__  )/ /  / // /_/ // /_/ /  ____/ /
#  /_/  |_|\___/ \___/ \___//____//____//_/  /_/ \____/ \__,_/  /_____/
## General parameters and configuration list 

# load main packages.

source('loadlib.R')
source('tools/R/amFunctions.R') 
source('tools/r/amProgress.R')
source('tools/R/amDataManage.R')
source('tools/R/amAnalysis.R')
source('tools/R/amHandson.R')
source('tools/R/amUi.R')



#CRAN



# output config list:
config<-list()


config$maxUploadSize = 300

# shiny options 
options(
  shiny.maxRequestSize = config$maxUploadSize*1024^2 
  #,shiny.trace=TRUE
  )


#used in update script.
config$repository="https://github.com/fxi/AccessMod_shiny"


#Paths
# base directory.
config$pathModule<-normalizePath('modules/')
config$pathGrassHome<-normalizePath('../logs/')
config$pathGrassDataBase<-normalizePath('../data/grass/')
config$pathCacheDir<-normalizePath('../data/cache')
# as we use packrat now, no need for additional libs
#config$pathLib<-normalizePath('../libs/')
# set local lib as first choice:
#.libPaths( c(config$pathLib, .libPaths())) 
# sqlite database
# get sqlite path after grass init : system(paste("echo",sqliteDB),intern=TRUE)
config$pathSqliteDB<-'$GISDBASE/$LOCATION_NAME/$MAPSET/sqlite.db'


# create directories if necessary.
dir.create(showWarnings=F,recursive=T,config$pathGrassDataBase)
dir.create(showWarnings=F,config$pathGrassHome)
#dir.create(showWarnings=F,config$pathLib)
dir.create(showWarnings=F,config$pathCacheDir)


# set other grass variables
# TODO: check if is use:
#grassMapset<-"PERMANENT"
grassRcFile<-file.path(config$pathGrassHome,'.grassrc6')
# unset gis_lock on startup
#unset.GIS_LOCK()

# standard dem name. Default project grid. 
config$mapDem<-"rDem__dem@PERMANENT"

# grass binaries and libs
config$os<-Sys.info()['sysname']

switch(config$os,
  'Darwin'={
    config$pathGrassBase70="/usr/local/Cellar/grass-70/7.0.0/grass-7.0.0"
    config$pathGrassBase64="/usr/local/Cellar/grass-64/6.4.4_1/grass-6.4.4"

  },
  "Linux"={
    config$pathGrassBase70="/usr/local/grass-7.0.0"
    config$pathGrassBase64="/usr/lib/grass64"
  } 
  )


# store archive in mapset. Path generated inside a GRASS environment only.
# get archive path  ex. system(paste("echo",archives),intern=TRUE)
config$pathArchiveGrass<-'$GISDBASE/$LOCATION_NAME/$MAPSET/accessmodArchives'
# name from the web server
config$archiveBaseName<-'accessmodArchive'
# get ovelaps dir
config$pathShapes<-'$GISDBASE/$LOCATION_NAME/$MAPSET/accessmodShapes'

# log file. Create it does not exist 
config$pathLog<-normalizePath(file.path(config$pathGrassHome,'logs.txt'))
#config$pathLogTest<-normalizePath(file.path(config$pathGrassHome,'test.txt'))
if(!file.exists(config$pathLog)) write("",config$pathLog)


#global variables
config$amLocation<-""
config$amTitle<-'Accessmod 5.0' # todo : include GIT version.

#standard message 
# TODO: These message are depreciated. Check and update function where they are used.
# TODO: create real localisation ?  (*.po/*.mo) 
config$msgNoLocation=list(en="Please select or create a project")
config$msgNoLocMapset=list(en="Please select or create project.")
config$msgNoProj<-'No projection information found. Make sure your dataset contains such information : .prj file, adf.prj, worldFile, complete metadata or similar.'
config$msgNotMetric<-'No metric projection information found. Make sur your dataset is projected using a metric coordinate system.'


# Registery of encountered errors NOT GENERATED BY ACCESSMOD. 
# Add new hint and translation in human language to avoid users to panic.
# This list, with function errHandler(), should dispatch current error to warning, log, or error condition.
# only warning and error (as set here or in amMsg() function) will create an alert for the user.
# structure :
# a. cond : hint of the registered condition. As the condition could be concatenated: (e.g. "SimpleWarning: 23 feature missing in map coverage@demo500m" ), extract only the useful part: "feature missing in map".  
# b. desc : Description to understand the error from the developer point of view.
# c. type : how accessMod should interprets the condition : log or error ?
# c. text : replacement text for the user.

config$msgTableError<-as.data.frame(rbind(
    c(
      cond="Field <projection> missing",
      desc="Can be produced when grass didn't found location metadata after g.region -3 -c. Need for reloading them from DEM",
      type='error',
      text="AccessMod did not recognize meta data for the current project. Please reload them in settings module:button 'Reload spatial settings'"),
    c(
      cond="is a base map for",
      desc="small warning when removing tmp map used in mask.",
      type='log',
      text='base map removed'
      ),
    c(
      cond= "No areas selected from vector map",
      desc=" v.to.rast warning if convert area is selected, but not found in geometries.",
      type='log',
      text='Vector map conversion to raster without area'
      ),
    c(
      cond="Datum <unknown>",
      desc=" maybe a wrong text. TODO: control this one. The text could be the original message.",
      type='log',
      text='Datum <unknown> not recognised by GRASS'
      ),
    c(
      cond="file does not exists",
      desc="Error after upload wrong file (type doesn't match extension, no metadata) OR error during gdal operation OR shiny internal fileUpload i/o problem.",
      type="error",
      text="file not recognized, make sure you have uploaded a supported raster files, with all its dependencies."
      ),
    c(
      cond="already exists and",
      desc= "Warning/error that occurs  with flag 'overwrite' and map exists.", 
      type="log",
      text="Map has been overwritten"
      ),
    c(
      cond="had status 1",
      desc=" generic error : could be everything. For now, tell the users it could be due to a bad formated dataset.",
      type="Error",
      text="Process has been aborded. Check your data for anomalies, e.g.: extent, CRS, non-conform values."
      ),
    c(
      cond="not appear to match current location",
      desc=" if the map crs is clearly wrong",
      type="error",
      text="The map CRS did not match current location."
      ),
    c(
      cond="Cannot create a RasterLayer object from this file",
      desc=" Error during importation if the package raster cant read metadata.",
      type="error",
      text="File not recognized, make sure you have loaded a supported raster map format, with all dependencies."
      ),
    c(
      cond="were not modified because modification would damage",
      desc= "v.clean say that some features has not ben cleaned to preserve topology",
      type='log',
      text='v.clean topology warning : some features have not been cleaned'
      ),
    c(
      cond="are written only when -c flag is given",
      desc='Warning when exporting empty area (inner rings) to shapefile',
      type="log",
      text="v.out.ogr found empty area (inner rings) to export in shapefile."
      ),
    c(
      cond="WARNING: Number of duplicate centroids",
      desc='duplicate centroids',
      type="log",
      text="v.in.ogr found duplicate centroïd"
      ),
    c(
      cond="Column name <cat> renamed to <cat_>",
      desc='Grass use <cat> as index column name. Any atribute table with <cat> as column name will be renamed to <cat_>',
      type="log",
      text="Column name <cat> renamed to <cat_>"
      ),
    c(
      cond="Input data contains 3D features",
      desc="Vector map uploaded contain 3d features. As accessmod works in 3d, ignoring 3d with -2 flag",
      type="log",
      text="Accessmod has converted 3D features in 2D."
      )
    # c(
    #   # NOTE: this error is really common and should not be redirected to log, as it could happen elsewhere.
    #   # in this case, it was from a xml parser in rgrass7 : simpleWarning in if (as.integer(opi) == opi) {: the condition has length > 1 and only the first element will be used
    #   cond="and only the first element will be used",
    #   desc="rgrass7 bug. cant pass multiple integer as paramameters without a warning.",
    #   type='log',
    #   text='rgrass bug. cant pass multiple integer as parameters. (ex.r.rescale.eq, c(1,100))'
    #   )
    )
  )


# verbose mode. 
# TODO: check if this is used
config$verbMod<-TRUE

# file extension allowed See also validateFilExt in fun/helper.R
config$fileAdf<-c('dblbnd.adf','hdr.adf','prj.adf','vat.adf','w001001.adf','w001001x.adf')
config$fileAdfMin<-c('prj.adf','w001001.adf','hdr.adf')
config$fileShpExt<-c('.shp','.dbf','.prj','.sbn','.sbx','xml','.shx')
config$fileShpExtMin<-c('.shp','.prj','.dbf','.shx')
config$fileImgMin<-c('.img')
config$filesAccept<-list(
  "vector"=c('.sqlite','.spatialite',config$fileShpExt),
  "raster"=c('.adf','.geotiff','.GeoTIFF','.tiff','.img'),
  "table"=c('.xls','.csv','.xlsx','.ods','.tsv','.dta','.psv','.dbf','.rds','.RData','.json','.xml')
  )
config$fileAcceptMultiple<-list(
  "vector" = TRUE,
  "raster" = TRUE,
  "table" = FALSE 
  )



# TODO: use id instead of class.. Check if this is possible in upload function.

config$tableColNames<-list(
  'tScenario'=c('class','label','speed','mode'),
  'tLandCover'=c('class','label'),
  'tStackRoad'=c('class','label'),
  'tStack'=c('class','label'),
  'tCapacity'=c('min','max','label','capacity'),
  'tExclusion'=c('layer','buffer','method')
  )

config$tableColType<-list(
  'tScenario'=c('integer','character','integer','character'),
  'tLandCover'=c('integer','character'),
  'tStackRoad'=c('integer','character'),
  'tCapacity'=c('numeric','numeric','character','numeric'),
  'tExclusion'=c('character','numeric','character')
  )


# new implementation by class id
config$dataFields <- list(
  # scaling up - new facility vector
  'vFacilityNew'=list(
    "amCapacity"="integer",
    "amName"="character",
    "amPopTimeMax"="integer"
    )
  )


# table of data class.
# id : identifier. Do not modify.
# class : class name visible by the user, used to create data names. Could be changed.
# type : raster, vector, table, report
# color : default grass color table (for raster)
# allowNew : visible in new data import
# internal : hidden from in manage data
#config$dataClass<-read.table(text=paste("
#    id               , class                          , type   , colors       , allowNew , internal\n
#    amLcv            , land_cover                     , raster , random       , TRUE     , FALSE\n
#    amLcvM           , land_cover_merged              , raster , random       , TRUE     , FALSE\n
#    amLcvMB          , land_cover_merged_bridge       , raster , random       , FALSE    , TRUE\n
#    amPop            , population                     , raster , population&e , TRUE     , FALSE\n
#    amPopRes         , population_residual            , raster , population&e , FALSE    , FALSE\n
#    amPopBar         , population_on_barrier          , raster , population&e , FALSE    , FALSE\n
#    amBar            , barrier                        , vector ,              , TRUE     , FALSE\n
#    amRoad           , road                           , vector ,              , TRUE     , FALSE\n
#    amHf             , health_facilities              , vector ,              , TRUE     , FALSE\n
#    amHfCatch        , health_facilities_catchment    , shape  ,              , FALSE    , FALSE\n
#    amPotCov         , potential_coverage             , raster ,              , FALSE    , FALSE\n
#    amZone           , zone_for_stat                  , vector ,              , TRUE     , FALSE\n
#    amSpeed          , speed                          , raster , bcyr&e       , FALSE    , TRUE\n
#    amFric           , friction                       , raster , bcyr&e       , FALSE    , TRUE\n
#    amCumCost        , travel_time                    , raster , slope        , FALSE    , FALSE\n
#    amLcvTable       , table_land_cover               , table  ,              , TRUE     , FALSE\n
#    amModTable       , table_scenario                 , table  ,              , TRUE     , FALSE\n
#    amRefTable       , table_referral                 , table  ,              , FALSE    , FALSE\n
#    amRefTableDist   , table_referral_nearest_by_dist , table  ,              , FALSE    , FALSE\n
#    amRefTableTime   , table_referral_nearest_by_time , table  ,              , FALSE    , FALSE\n
#    amCapTable       , table_capacity                 , table  ,              , FALSE    , FALSE\n
#    amZoneCovTable   , table_zonal_coverage           , table  ,              , FALSE    , FALSE\n
#    amStackRoad      , stack_road                     , raster , random       , FALSE    , TRUE\n
#    amStackLcv       , stack_land_cover               , raster , random       , FALSE    , TRUE\n
#    amStackBar       , stack_barrier                  , raster , random       , FALSE    , TRUE\n
#    amScalFacility   , scaling_up_new_facilities      , vector ,              , FALSE    , FALSE\n
#    amScalCapTable   , scaling_up_capacity            , table  ,              , TRUE     , FALSE\n
#    amScalExclTable  , scaling_up_exclusion           , table  ,              , TRUE     , FALSE\n
#    amScalSuitTable  , scaling_up_suitability         , table  ,              , TRUE     , FALSE\n
#    amScalProxi      , scaling_up_proximity_ref       , vector ,              , TRUE     , FALSE\n
#    amScalPriority   , scaling_up_priority            , raster ,              , TRUE     , FALSE\n
#    amScalExcluR     , scaling_up_exclusion_rast      , raster ,              , TRUE     , FALSE\n
#    amScalExcluV     , scaling_up_exclusion_vect      , vector ,              , TRUE     , FALSE\n
#    amDem            , dem                            , raster , elevation    , TRUE     , FALSE\n
#    "),
#    sep=',',
#    header=TRUE,
#    colClasses=c('character','character','character','character','logical','logical'),
#    strip.white=TRUE
#    )
#


# data classes. 
# id data id, never change. 
# en = english name. 
# type= raster,vector,table.
# colors = grass color palette
# allowNew = allow the user to upload new
# internal = used internally, not showing to lambda user
config$dataClass<-read.table(text=paste("
    class                , en                       , type   , colors       , allowNew , internal\n
    rDem                 , dem                      , raster , elevation    , TRUE     , FALSE\n
    rLandCover           , land cover               , raster , random       , TRUE     , FALSE\n
    rLandCoverMerged     , land cover merged        , raster , random       , TRUE     , FALSE\n
    rLandCoverBridge     , land cover merged bridge , raster , random       , FALSE    , TRUE\n
    rPopulation          , population               , raster , population&e , TRUE     , FALSE\n
    rPopulationResidual  , population residual      , raster , population&e , FALSE    , FALSE\n
    rSpeed               , speed                    , raster , bcyr&e       , FALSE    , TRUE\n
    rFriction            , friction                 , raster , bcyr&e       , FALSE    , TRUE\n
    rTravelTime          , travel time              , raster , slope        , FALSE    , FALSE\n
    rPopulationOnBarrier , population on barrier    , raster , population&e , FALSE    , FALSE\n
    rStackRoad           , stack road               , raster , random       , FALSE    , TRUE\n
    rStackLandCover      , stack land cover         , raster , random       , FALSE    , TRUE\n
    rStackBarrier        , stack barrier            , raster , random       , FALSE    , TRUE\n
    rPriority            , priority                 , raster ,              , TRUE     , FALSE\n
    rExclusion           , exclusion                , raster ,              , TRUE     , FALSE\n
    rCoveragePotential   , potential coverage       , raster ,              , FALSE    , FALSE\n
    vBarrier             , barrier                  , vector ,              , TRUE     , FALSE\n
    vRoad                , road                     , vector ,              , TRUE     , FALSE\n
    vFacility            , facility                 , vector ,              , TRUE     , FALSE\n
    vFacilityNew         , facility scaling up      , vector ,              , FALSE    , FALSE\n
    vZone                , zone for stat            , vector ,              , TRUE     , FALSE\n
    vExclusion           , exclusion                , vector ,              , TRUE     , FALSE\n
    tExclusion           , exclusion                , table  ,              , TRUE     , FALSE\n
    tExclusionOut        , exclusion processed      , table  ,              , FALSE    , FALSE\n
    tLandCover           , land cover               , table  ,              , TRUE     , FALSE\n
    tScenario            , scenario                 , table  ,              , TRUE     , FALSE\n
    tScenarioOut         , scenario processed       , table  ,              , FALSE    , FALSE\n
    tReferral            , referral                 , table  ,              , FALSE    , FALSE\n
    tReferralDist        , referral by dist         , table  ,              , FALSE    , FALSE\n
    tReferralTime        , referral nearest by time , table  ,              , FALSE    , FALSE\n
    tCapacity            , capacity                 , table  ,              , TRUE     , FALSE\n
    tCapacityOut         , capacity processed       , table  ,              , FALSE    , FALSE\n
    tCapacityStat        , capacity analysis        , table  ,              , FALSE    , FALSE\n
    tZonalStat           , zonal coverage           , table  ,              , FALSE    , FALSE\n
    tSuitability         , suitability              , table  ,              , TRUE     , FALSE\n
    tSuitabilityOut      , suitability processed    , table  ,              , FALSE    , FALSE\n
    tStack               , stack                    , table  ,              , FALSE    , TRUE\n
    tStackRoad           , stack road               , table  ,              , FALSE    , TRUE\n
    vCatchment           , catchment                , shape  ,              , FALSE    , FALSE\n
    "),
    sep=",",
    header=TRUE,
    colClasses=c("character","character","character","character","logical","logical"),
    strip.white=TRUE
    )


config$language = "en"
config$dataClassList <- dlply(config$dataClass,.(class),c)




  config$dynamicFacilities <- "[ NEW FACILITIES ]"
  config$dynamicPopulation <- "[ NEW POPULATION ]"

  # character separator
  config$sepTagUi='+' #NOTE: depreciated. Using sepTagFile or tags in bracket.
  config$sepTagFile='_'
  config$sepClass='__'
  config$sepTagRepl=' '
  config$sepMapset='@' 

  # max row table preview 
  #NOTE: used only in road table, to prevent thousand combination of cat/label in table.
  config$maxRowPreview<-50

  # allowed mode of transportation. As required by r.walk.accessmod.
  # KEYWORD=list(raster value=<key value to distinguish mode from speed>)
  config$listTranspMod<-list(
    WALKING=list(rastVal=1000),
    BICYCLING=list(rastVal=2000),
    MOTORIZED=list(rastVal=3000)
    )

  config$defaultTranspMode = "WALKING"


  # color palettes #NOTE: depreciated. Use config$dataClass['colors'] instead.
  config$paletteBlue<-colorRampPalette(c("#FFFFFF","#8C8CB2","#004664","#000632","#000000"))


  # icons
  # icon/favicon, defined in ui.R
  config$iconSmall<-img(src="logo/icons/logo24x24.png")
  config$iconMedium<-img(src="logo/icons/logo32x32.png")
  config$iconLarge<-img(src="logo/icons/logo128x128.png")
  config$iconHuge<-img(src="logo/icons/logo648x648.png")
  config$iconWhoSvg<-img(src="logo/who.svg",style="width:100%; max-height:40px;")
  config$iconWho<-img(src="logo/icons/WHO-EN-C-H.png")
  config$iconWhoSmall<-img(src="logo/icons/WHO-EN-C-H_small.png",width='95%')


  # 
  config$helpTitle = tags$span(icon("info-circle"),"AccessMod 5")

  # progress bar
  # default id
  config$pBarId = "pbar"
  # default time out
  config$pBarTimeOut = 2


  # order config list
  config<-config[sort(names(config))]

 # scaling up range of suitability
  config$scalingUpRescaleRange = c(0L,10000L)

