
variable "cpus" {
  type    = string
  default = "2"
}

variable "disk_size" {
  type    = string
  default = "40960"
}

variable "hub_api" {
  type    = string
  default = "https://hub.docker.com/v2/"
}

variable "image" {
  type    = string
  default = "fredmoser/accessmod:latest"
}

variable "repo" {
  type    = string
  default = "fredmoser/accessmod"
}

variable "iso_checksum" {
  type    = string
  default = "2f46f2340ba82763e10984a56dd4bd9002f8cd12f45d617bb81a7597d2033250"
}

variable "iso_checksum_type" {
  type    = string
  default = "sha256"
}

variable "iso_local_url" {
  type    = string
  default = "iso/alpine-virt-3.14.8-x86_64.iso"
}

variable "iso_url" {
  type    = string
  default = "https://dl-cdn.alpinelinux.org/alpine/v3.14/releases/x86_64/alpine-virt-3.14.8-x86_64.iso"
}

variable "memory" {
  type    = string
  default = "4096"
}

variable "port_app" {
  type    = string
  default = "3000"
}

variable "port_app_public" {
  type    = string
  default = "8080"
}

variable "port_http" {
  type    = string
  default = "5000"
}

variable "port_http_public" {
  type    = string
  default = "8888"
}

variable "port_ssh" {
  type    = string
  default = "22"
}

variable "port_ssh_public" {
  type    = string
  default = "2222"
}


variable "root_password" {
  type    = string
  default = "accessmod"
}

variable "ssh_password" {
  type    = string
  default = "accessmod"
}

variable "ssh_username" {
  type    = string
  default = "accessmod"
}

variable "version" {
  type    = string
  default = "5.8.1"
}
variable "vm_version" {
  type    = string
  default = "5.8"
}

variable "vm_name" {
  type    = string
  default = "alpine-accessmod"
}




source "virtualbox-iso" "autogenerated_1" {
  boot_command = [
    "root<enter><wait>",
    "ifconfig eth0 up && udhcpc -i eth0<enter><wait5>",
    "wget http://{{ .HTTPIP }}:{{ .HTTPPort }}/alpine_setup<enter><wait>",
    "export USEROPTS='-a -u -g audio,video,netdev ${var.ssh_username}'<enter>",
    "export USERSSHKEY='http://{{ .HTTPIP }}:{{ .HTTPPort }}/ssh_keys'<enter>",
    "export ROOTSSHKEY='http://{{ .HTTPIP }}:{{ .HTTPPort }}/ssh_keys'<enter>",
    "setup-alpine -f $PWD/alpine_setup<enter><wait5>",
    "${var.ssh_password}<enter><wait>",
    "${var.ssh_password}<enter><wait30>",
    "mount /dev/sda3 /mnt<enter>",
    "echo 'PermitRootLogin yes' >> /mnt/etc/ssh/sshd_config<enter>",
    "umount /mnt; reboot<enter>"
  ]
  boot_wait            = "10s"
  communicator         = "ssh"
  disk_size            = "${var.disk_size}"
  format               = "ova"
  guest_additions_mode = "disable"
  guest_os_type        = "Linux26_64"
  headless             = true
  http_directory       = "http"
  iso_checksum         = "${var.iso_checksum_type}:${var.iso_checksum}"
  iso_urls             = ["${var.iso_local_url}", "${var.iso_download_url}"]
  keep_registered      = "true"
  shutdown_command     = "/sbin/poweroff"
  ssh_password         = "${var.ssh_password}"
  ssh_port             = "${var.port_ssh_public}"
  ssh_timeout          = "10m"
  ssh_username         = "${var.ssh_username}"
  vboxmanage = [
    ["modifyvm", "{{ .Name }}", "--memory", "${var.memory}"],
    ["modifyvm", "{{ .Name }}", "--cpus", "${var.cpus}"],
    ["modifyvm", "{{ .Name }}", "--rtcuseutc", "on"],
    ["modifyvm", "{{ .Name }}", "--graphicscontroller", "vmsvga"],
    ["modifyvm", "{{ .Name }}", "--vram", "6"],
    ["modifyvm", "{{ .Name }}", "--vrde", "off"],
    ["modifyvm", "{{ .Name }}", "--nic1", "nat"],
    ["modifyvm", "{{ .Name }}", "--natpf1", "accessmod_app,tcp,0.0.0.0,${var.port_app_public},0.0.0.0,${var.port_app}"],
    ["modifyvm", "{{ .Name }}", "--natpf1", "accessmod_http,tcp,0.0.0.0,${var.port_http_public},0.0.0.0,${var.port_http}"],
    ["modifyvm", "{{ .Name }}", "--natpf1", "accessmod_ssh,tcp,0.0.0.0,${var.port_ssh_public},0.0.0.0,${var.port_ssh}"],
    ["modifyvm", "{{ .Name }}", "--nictype1", "virtio"],
    ["modifyvm", "{{ .Name }}", "--nictype2", "virtio"],
    ["modifyvm", "{{ .Name }}", "--nictype3", "virtio"],
    ["modifyvm", "{{ .Name }}", "--chipset", "ich9"],
    ["modifyvm", "{{ .Name }}", "--ioapic", "on"],
    ["modifyvm", "{{ .Name }}", "--usb", "off"],
    ["modifyvm", "{{ .Name }}", "--usbehci", "off"]
  ]
  vm_name = "${var.vm_name}-${var.vm_version}"
}



build {
  description = "Build base Alpine Linux x86_64"
  sources     = ["source.virtualbox-iso.autogenerated_1"]

  provisioner "file" {
    source      = "scripts"
    destination = "/tmp/scripts"
  }

  provisioner "shell" {
    script = "scripts/provision.sh"
    environment_vars = [
      "SSH_USERNAME=${var.ssh_username}",
      "SSH_PASSWORD=${var.ssh_password}",
      "ALPINE_REPOSITORY=http://dl-cdn.alpinelinux.org/alpine/v3.14/community",
      "AM5_PORT_APP=${var.port_app}",
      "AM5_PORT_APP_PUBLIC=${var.port_app_public}",
      "AM5_PORT_HTTP=${var.port_http}",
      "AM5_PORT_HTTP_PUBLIC=${var.port_http_public}",
      "AM5_ARCHIVE_DOCKER=/home/accessmod/accessmod-docker.tar.gz",
      "AM5_SCRIPTS_FOLDER=/home/accessmod/scripts",
      "AM5_VERSION_FILE=/home/accessmod/version",
      "AM5_VERSION=${var.version}",
      "AM5_REPO=${var.repo}",
      "AM5_HUB_API=${var.hub_api}",
      "AM5_IMAGE=${var.image}"
    ]
  }
}
