# Registry of encountered errors NOT GENERATED BY ACCESSMOD.
# Add new hint and translation in human language to avoid users to panic.
# This list, with function amErrHandler(), dispatches conditions to warning,
# log, or error.  Only warning and error will create an alert for the user.
#
# Structure:
#   cond : substring to match against the condition message
#   desc : developer-facing explanation
#   type : how AccessMod interprets it — "log", "warning", "error", "discarded"
#   text : translation key (looked up via ams()) or fallback literal string

config$msgTableError <- as.data.frame(rbind(
  c(
    cond = "simpleWarning",
    desc = "grass send a simpleWarning, nothing important",
    type = "discarded",
    text = ""
  ),
  c(
    cond = "pBarQuit",
    desc = "The user pressed the exit button in the progressbar panel",
    type = "warning",
    text = "The user requested the end of the process."
  ),
  c(
    cond = "Projection of dataset does not appear to match current",
    desc = "Projection does not match",
    type = "error",
    text = "The projection of this dataset does not appear to match current project"
  ),
  c(
    cond = "Field <projection> missing",
    desc = "Can be produced when grass didn't found location metadata after g.region -3 -c. Need for reloading them from DEM",
    type = "error",
    text = "AccessMod did not recognize meta data for the current project. Please reload them in settings module:button 'Reload spatial settings'"
  ),
  c(
    cond = "is a base map for",
    desc = "small warning when removing tmp map used in mask.",
    type = "log",
    text = "base map removed"
  ),
  c(
    cond = "No areas selected from vector map",
    desc = " v.to.rast warning if convert area is selected, but not found in geometries.",
    type = "log",
    text = "Vector map conversion to raster without area"
  ),
  c(
    cond = "Datum <unknown>",
    desc = " maybe a wrong text. TODO: control this one. The text could be the original message.",
    type = "log",
    text = "Datum <unknown> not recognised by GRASS"
  ),
  c(
    cond = "file does not exists",
    desc = "Error after upload wrong file (type doesn't match extension, no metadata) OR error during gdal operation OR shiny internal fileUpload i/o problem.",
    type = "error",
    text = "file not recognized, make sure you have uploaded a supported raster files, with all its dependencies."
  ),
  c(
    cond = "already exists and",
    desc = "Warning/error that occurs  with flag 'overwrite' and map exists.",
    type = "log",
    text = "Map has been overwritten"
  ),
  c(
    cond = "had status 1",
    desc = " generic error : could be everything. For now, tell the users it could be due to a bad formated dataset.",
    type = "Error",
    text = "Process has been aborded. Check your data for anomalies, e.g.: extent, CRS, non-conform values."
  ),
  c(
    cond = "Cannot create a RasterLayer object from this file",
    desc = " Error during importation if the package raster cant read metadata.",
    type = "error",
    text = "File not recognized, make sure you have loaded a supported raster map format, with all dependencies."
  ),
  c(
    cond = "were not modified because modification would damage",
    desc = "v.clean say that some features has not ben cleaned to preserve topology",
    type = "log",
    text = "v.clean topology warning : some features have not been cleaned"
  ),
  c(
    cond = "are written only when -c flag is given",
    desc = "Warning when exporting empty area (inner rings) to shapefile",
    type = "log",
    text = "v.out.ogr found empty area (inner rings) to export in shapefile."
  ),
  c(
    cond = "WARNING: Number of duplicate centroids",
    desc = "duplicate centroids",
    type = "log",
    text = "v.in.ogr found duplicate centroïd"
  ),
  c(
    cond = "Column name <cat> renamed to <cat_>",
    desc = "Grass use <cat> as index column name. Any atribute table with <cat> as column name will be renamed to <cat_>",
    type = "log",
    text = "Column name <cat> renamed to <cat_>"
  ),
  c(
    cond = "Input data contains 3D features",
    desc = "Vector map uploaded contain 3d features. As accessmod works in 3d, ignoring 3d with -2 flag",
    type = "log",
    text = "Accessmod has converted 3D features in 2D."
  ),
  c(
    cond = "Mixing IDs of areas and primitives",
    desc = "v.out.ogr error: category IDs shared between area centroids and primitives — topology defect in source shapefile",
    type = "error",
    text = "err_vector_topology_mixing_ids"
  ),
  c(
    cond = "topology_mixed_area_primitive",
    desc = "Post-import check: polygon layer has both area and line primitives — will likely fail export",
    type = "warning",
    text = "warn_vector_topology_mixed"
  )
))
