#      ___                                  __  ___            __   ______
#     /   |  _____ _____ ___   _____ _____ /  |/  /____   ____/ /  / ____/
#    / /| | / ___// ___// _ \ / ___// ___// /|_/ // __ \ / __  /  /___ \
#   / ___ |/ /__ / /__ /  __/(__  )(__  )/ /  / // /_/ // /_/ /  ____/ /
#  /_/  |_|\___/ \___/ \___//____//____//_/  /_/ \____/ \__,_/  /_____/
#
# Module manage_data 
#
# USER INTERFACE

fluidRow(
  div(class="col-xs-12 col-md-4",
    amAccordionGroup(id='manageData',itemList=list(
        'addData'=list(
          title=div(icon('plus-circle'),'Import'),
          content=tagList(
            selectInput('dataClass','Select data class:',choices=""),
            textInput('dataTag','Add short tags',value=''),
            uiOutput('msgModuleData'),
            amFileInput('btnDataNew',label='Choose and import data') 
            )
          ),
        'filtData'=list(
          title=div(icon('filter'),'Filter'),
          content=tagList(
            radioButtons('typeDataChoice','Data type',
              c("Vectors" = "vector",
                "Rasters" = "raster",
                "Tables"  = "table",
                "Lists"  = "list",
                "All"    = "all"),
              selected   = "all",
              inline=TRUE
              ),
            textInput(inputId = 'filtData','Text (any field, case sensitive)',''), 
            selectInput(inputId = 'filtDataTags','Tags filter',choices='',selected='',multiple=T), 
            conditionalPanel(condition="input.showAdvancedTools==true",
            checkboxInput("internalDataChoice",'Show internal data',value=FALSE)
            )
            )      
          ),
        'renameData'=list(
          title=div(icon('refresh'),'Rename'),
          content=tagList(
            #h4('Rename changed tags'),
            p('Manually modify the tag(s) in the adjacent table and click on the button to implement the change (does not work with the DEM)'),
            actionButton('btnUpdateName','Update modified tag(s)')
            )
          ),
        'archiveData'=list(
          title=div(icon('compress'),'Archive'),
          content= tagList(
            p('Click to archive (.zip) the data appearing as selected in the right table'),
            actionButton('createArchive','Create archive')
            )
          ),
        'exportData'=list(
          title=div(icon('download'),'Export'),
          content=tagList(
            #h4('Export selected archive'),
            selectInput('selArchive','Select archive',choices=""),
            actionButton('getArchive','Export archive')
            )
          ),
        'remData'=list(
          title=div(icon('trash-o'),'Delete'),
          content=tagList(
            p('This action will delete the selected data'),
            actionButton('delDataSelect','Delete permanently'),
            p(id="txtDelMessage","")
            )
          )
        )) 
    ),
  div(class="col-xs-12 col-md-8",
      amCenterTitle('Available data',sub="Data imported in the project or generated by AccessMod."),
      actionLink('btnSelectAllData','All',icon=icon('check-square-o'),
        onclick="hotableSetColValues('dataListTable','Select',true)"
        ),'|',
      actionLink('btnSelecteNoData','None',icon=icon('square-o'), 
        onclick="hotableSetColValues('dataListTable','Select',false)"
        ),
      hotable('dataListTable')
    )
  )


